#!/usr/bin/env bash

# This simple script should create the basic environment for
# EVM in the user's HOME if EVM_HOME is not set

if [[ -z "$EVM_HOME" ]]; then
  EVM_HOME="$HOME/.evm"
fi
DIRS="tars versions config scripts"

type wget >/dev/null 2>/dev/null
if [[ $? -eq "1" ]]; then
  echo "Could not complete installation of evm."
  echo "Please install wget."
  exit 1
else
  echo "wget found!"
fi

# For each dir, check whether it's already exists or not
for dir in $DIRS; do
  if [[ ! -d "$EVM_HOME/$dir" ]]; then
    mkdir -p "$EVM_HOME/$dir"
    echo "$EVM_HOME/$dir successfully created"
  else
    echo "$EVM_HOME/$dir already exists and will not be replaced"
  fi
done

# Create the config file
if [[ ! -f "$EVM_HOME/config/default" ]]; then
  touch "$EVM_HOME/config/default"
  echo "$EVM_HOME/config/default succesfully created"
else
  echo "$EVM_HOME/config/default already exists and will not be replaced"
fi

# Copy the script
cp -f "$PWD/evm" "$EVM_HOME/scripts"

echo
echo "
           _______________   ____ _____                    
           \_   _____/\   \ /   //     \                   
   ______   |    __)_  \   Y   //  \ /  \    ______        
  /_____/   |        \  \     //    Y    \  /_____/        
           /_______  /   \___/ \____|__  /                 
                   \/                  \/                  
 ___________        .__                                    
 \_   _____/_______ |  |  _____     ____    ____           
  |    __)_ \_  __ \|  |  \__  \   /    \  / ___\          
  |        \ |  | \/|  |__ / __ \_|   |  \/ /_/  >         
 /_______  / |__|   |____/(____  /|___|  /\___  /          
         \/                    \/      \//_____/           
 ____   ____                     .__                       
 \   \ /   / ____ _______  ______|__|  ____    ____        
  \   Y   /_/ __ \\\\_  __ \/  ___/|  | /  _ \  /    \\       
   \     / \  ___/ |  | \/\___ \ |  |(  <_> )|   |  \      
    \___/   \___  >|__|  /____  >|__| \____/ |___|  /      
                \/            \/                  \/       
    _____                                                  
   /     \  _____     ____  _____     ____    ____ _______ 
  /  \ /  \ \__  \   /    \ \__  \   / ___\ _/ __ \\\\_  __ \\
 /    Y    \ / __ \_|   |  \ / __ \_/ /_/  >\  ___/ |  | \/
 \____|__  /(____  /|___|  /(____  /\___  /  \___  >|__|   
         \/      \/      \/      \//_____/       \/       
"
echo
echo "Execute 'source $EVM_HOME/scripts/evm' or add that to your ~/.bashrc or ~/.zshrc file"
